### ISSUE TITLE
address lookup field clunky when apartment number entered

### ISSUE THREAD

**Issue by davidmooreppf** [nysenate/NYSenate.gov#14] opened 2019-04-09 01:17 UTC
Testing new account registration on Chrome on OS 10.14.3. 

On user registration page: https://www.nysenate.gov/registration/nojs/form/start

First, entering my full street address did not auto-find my city, state, zip. That could have been because my full address has an apartment number and lookup stopped after I entered "1R", worth testing. 

Second, when I did delete my apartment number and tried to get city, state, zip to appear, it was hidden behind Chrome auto-fill suggestion drop-down, could be confusing to new users.

I'll attach an image, my address is pretty public, ha. 

![image](https://user-images.githubusercontent.com/116819/55766650-94f67800-5a43-11e9-8642-66367cd52a54.png)

**Comment by davidmooreppf** [comment] 2019-04-09 02:05
![image](https://user-images.githubusercontent.com/116819/55768279-44364d80-5a4a-11e9-9d33-f3a526186019.png)

The behavior between the auto-suggest feature and the address lookup is a bit inconsistent, with and without apartment number, but note initially that the city-state-zip fields don't appear even when just the street address is entered with no apartment number.

**Comment by routinet** [comment] 2019-04-15 21:15
Hello,

First and foremost, thanks for taking the time to report this.  There appears to be two issues:

- both auto-complete boxes appearing at once
- clumsy UX with regards to address parsing/completion

The first issue, which we are addressing, is caused by browsers no longer respecting `autocomplete="off"` for an input element.  Furthermore, JS injected by Google as the autocompletion script is bound (places_impl.js) forcibly sets the autocomplete attribute to "off".  We are adding a mechanism to reset the value of the attribute during focus, which removes the browser's native auto-complete box.

Sadly, the second issue, "clumsy UX", is out of our hands.  The auto-completion, parsing, and locating of an address is all through Google's gmap scripts.  AFAIK, we cannot really affect the accuracy or utility in how they do their matching, so we're stuck with best-effort.

**Comment by rtblair** [comment] 2019-04-15 21:17
The fix for the first issue will deploy with the next release (sometime this week). It will make it into this public repository at a later date. Thanks again, @davidmooreppf.

**Comment by davidmooreppf** [comment] 2019-04-15 21:29
Makes good sense, thanks for the detailed response and the update, hope it's helpful for others. Close whenever!

**Comment by routinet** [comment] 2021-08-12 15:04
Repo updated in bulk. Closing outdated issues.

**Closed by routinet** 2021-08-12 15:04 UTC
